export const bloodGroup = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];
export const description = `This website would help Donors, as well as patients in need of plasma. We allow you to search plasma Donors within your city area and having a specific blood group. If you are a recipient get your self registered on the Website and help the society. We are all in this together and we will win as a community.`;

export const State = [
  {
    value: "35",
    label: "Andaman & Nicobar Islands",
    records: {
      records: [
        { id: "Nicobars", value: "638" },
        { id: "North  & Middle Andaman", value: "639" },
        { id: "South Andaman", value: "640" },
      ],
    },
  },
  {
    value: "28",
    label: "Andhra Pradesh",
    records: [
      { id: "Alluri Sitharama Raju", value: "679" },
      { id: "Anakapalli", value: "680" },
      { id: "Anantapur", value: "553" },
      { id: "Annamayya", value: "753" },
      { id: "Bapatla", value: "750" },
      { id: "Chittoor", value: "554" },
      { id: "East Godavari", value: "545" },
      { id: "Eluru", value: "748" },
      { id: "Guntur", value: "548" },
      { id: "Kakinada", value: "681" },
      { id: "Konaseema", value: "682" },
      { id: "Krishna", value: "547" },
      { id: "Kurnool", value: "552" },
      { id: "Nandyal", value: "755" },
      { id: "NTR", value: "749" },
      { id: "Palnadu", value: "751" },
      { id: "Parvathipuram Manyam", value: "743" },
      { id: "Prakasam", value: "549" },
      { id: "Srikakulam", value: "542" },
      { id: "Sri Potti Sriramulu Nellore", value: "550" },
      { id: "Sri Sathya Sai", value: "754" },
      { id: "Tirupati", value: "752" },
      { id: "Visakhapatnam", value: "544" },
      { id: "Vizianagaram", value: "543" },
      { id: "West Godavari", value: "546" },
      { id: "Y.S.R.", value: "551" },
    ],
  },
  {
    value: "12",
    label: "Arunachal Pradesh",
    records: [
      { id: "Anjaw", value: "260" },
      { id: "Changlang", value: "253" },
      { id: "Dibang Valley", value: "257" },
      { id: "East Kameng", value: "247" },
      { id: "East Siang", value: "251" },
      { id: "Itanagar Capital Complex", value: "299" },
      { id: "Kamle", value: "701" },
      { id: "Kra Daadi", value: "702" },
      { id: "Kurung Kumey", value: "256" },
      { id: "Lepa-Rada", value: "703" },
      { id: "Lohit", value: "259" },
      { id: "Longding", value: "642" },
      { id: "Lower Dibang Valley", value: "258" },
      { id: "Lower Siang", value: "704" },
      { id: "Lower Subansiri", value: "255" },
      { id: "Namsai", value: "678" },
      { id: "Pakke-Kessang", value: "706" },
      { id: "Papum Pare", value: "248" },
      { id: "Shi Yomi", value: "707" },
      { id: "Siang", value: "709" },
      { id: "Tawang", value: "245" },
      { id: "Tirap", value: "254" },
      { id: "Upper Siang", value: "252" },
      { id: "Upper Subansiri", value: "249" },
      { id: "West Kameng", value: "246" },
      { id: "West Siang", value: "250" },
    ],
  },
  {
    value: "18",
    label: "Assam",
    records: [
      { id: "Baksa", value: "324" },
      { id: "Barpeta", value: "303" },
      { id: "Bishwanath", value: "710" },
      { id: "Bongaigaon", value: "319" },
      { id: "Cachar", value: "316" },
      { id: "Charaideo", value: "711" },
      { id: "Chirang", value: "320" },
      { id: "Darrang", value: "325" },
      { id: "Dhemaji", value: "308" },
      { id: "Dhubri", value: "301" },
      { id: "Dibrugarh", value: "310" },
      { id: "Dima Hasao", value: "315" },
      { id: "Goalpara", value: "302" },
      { id: "Golaghat", value: "313" },
      { id: "Hailakandi", value: "318" },
      { id: "Hojai", value: "712" },
      { id: "Jorhat", value: "312" },
      { id: "Kamrup", value: "321" },
      { id: "Kamrup Metropolitan", value: "322" },
      { id: "Karbi Anglong", value: "314" },
      { id: "Karimganj", value: "317" },
      { id: "Kokrajhar", value: "300" },
      { id: "Lakhimpur", value: "307" },
      { id: "Majuli", value: "746" },
      { id: "Majuli", value: "713" },
      { id: "Morigaon", value: "304" },
      { id: "Nagaon", value: "305" },
      { id: "Nalbari", value: "323" },
      { id: "Sivasagar", value: "311" },
      { id: "Sonitpur", value: "306" },
      { id: "South Salmara", value: "714" },
      { id: "Tinsukia", value: "309" },
      { id: "Udalguri", value: "326" },
      { id: "West Karbi Anglong", value: "715" },
    ],
  },
  {
    value: "10",
    label: "Bihar",
    records: [
      { id: "Araria", value: "209" },
      { id: "Arwal", value: "240" },
      { id: "Aurangabad", value: "235" },
      { id: "Banka", value: "225" },
      { id: "Begusarai", value: "222" },
      { id: "Bhagalpur", value: "224" },
      { id: "Bhojpur", value: "231" },
      { id: "Buxar", value: "232" },
      { id: "Darbhanga", value: "215" },
      { id: "Gaya", value: "236" },
      { id: "Gopalganj", value: "217" },
      { id: "Jamui", value: "238" },
      { id: "Jehanabad", value: "239" },
      { id: "Kaimur (Bhabua)", value: "233" },
      { id: "Katihar", value: "212" },
      { id: "Khagaria", value: "223" },
      { id: "Kishanganj", value: "210" },
      { id: "Lakhisarai", value: "227" },
      { id: "Madhepura", value: "213" },
      { id: "Madhubani", value: "207" },
      { id: "Munger", value: "226" },
      { id: "Muzaffarpur", value: "216" },
      { id: "Nalanda", value: "229" },
      { id: "Nawada", value: "237" },
      { id: "Pashchim Champaran", value: "203" },
      { id: "Patna", value: "230" },
      { id: "Purba Champaran", value: "204" },
      { id: "Purnia", value: "211" },
      { id: "Rohtas", value: "234" },
      { id: "Saharsa", value: "214" },
      { id: "Samastipur", value: "221" },
      { id: "Saran", value: "219" },
      { id: "Sheikhpura", value: "228" },
      { id: "Sheohar", value: "205" },
      { id: "Sitamarhi", value: "206" },
      { id: "Siwan", value: "218" },
      { id: "Supaul", value: "208" },
      { id: "Vaishali", value: "220" },
    ],
  },
  {
    value: "94",
    label: "Chandigarh",
    records: [{ id: "Chandigarh", value: "55" }],
  },
  {
    value: "22",
    label: "Chhattisgarh",
    records: [
      { id: "Balod", value: "643" },
      { id: "Baloda Bazaar", value: "644" },
      { id: "Balrampur", value: "645" },
      { id: "Bastar", value: "414" },
      { id: "Bemetra", value: "646" },
      { id: "Bharatpur", value: "760" },
      { id: "Bijapur", value: "417" },
      { id: "Bilaigarh", value: "763" },
      { id: "Bilaspur", value: "406" },
      { id: "Dantewada", value: "416" },
      { id: "Dhamtari", value: "412" },
      { id: "Durg", value: "409" },
      { id: "Gariyaband", value: "647" },
      { id: "Gaurella Pendra Marwahi", value: "997" },
      { id: "Janjgir - Champa", value: "405" },
      { id: "Jashpur", value: "402" },
      { id: "Kabirdham", value: "407" },
      { id: "Kanker", value: "413" },
      { id: "Khairgarh Chhuikhadan Gandai", value: "759" },
      { id: "Kondagaon", value: "648" },
      { id: "Korba", value: "404" },
      { id: "Koriya", value: "400" },
      { id: "Mahasamund", value: "411" },
      { id: "Mungeli", value: "649" },
      { id: "Narayanpur", value: "415" },
      { id: "Raigarh", value: "403" },
      { id: "Raipur", value: "410" },
      { id: "Rajnandgaon", value: "408" },
      { id: "Sakti Sarangarh", value: "762" },
      { id: "Sukma", value: "651" },
      { id: "Surajpur", value: "650" },
      { id: "Surguja", value: "401" },
    ],
  },
  {
    value: "26",
    label: "Dadra & Nagar Haveli",
    records: [{ id: "Dadra & Nagar Haveli", value: "496" }],
  },
  {
    value: "25",
    label: "Daman & Diu",
    records: [
      { id: "Daman", value: "495" },
      { id: "Diu", value: "494" },
    ],
  },
  {
    value: "97",
    label: "Delhi",
    records: [
      { id: "Central", value: "95" },
      { id: "East", value: "93" },
      { id: "New Delhi", value: "94" },
      { id: "North", value: "91" },
      { id: "North East", value: "92" },
      { id: "North West", value: "90" },
      { id: "Shahdara", value: "653" },
      { id: "South", value: "98" },
      { id: "South East", value: "652" },
      { id: "South West", value: "97" },
      { id: "West", value: "96" },
    ],
  },
  {
    value: "30",
    label: "Goa",
    records: [
      { id: "North Goa", value: "585" },
      { id: "south Goa", value: "586" },
    ],
  },
  {
    value: "24",
    label: "Gujarat",
    records: [
      { id: "Ahmedabad", value: "474" },
      { id: "Amreli", value: "480" },
      { id: "Anand", value: "482" },
      { id: "Aravalli", value: "656" },
      { id: "Banas Kantha", value: "469" },
      { id: "Bharuch", value: "488" },
      { id: "Bhavnagar", value: "481" },
      { id: "Botad", value: "803" },
      { id: "Chhotaudepur", value: "655" },
      { id: "Dahod", value: "485" },
      { id: "Dang", value: "654" },
      { id: "Devbhoomi Dwarka", value: "717" },
      { id: "Gandhinagar", value: "473" },
      { id: "Gir Somnath", value: "718" },
      { id: "Jamnagar", value: "477" },
      { id: "Junagadh", value: "479" },
      { id: "Kachchh", value: "468" },
      { id: "Kheda", value: "483" },
      { id: "Mahesana", value: "471" },
      { id: "Mahisagar", value: "657" },
      { id: "Morbi", value: "676" },
      { id: "Narmada", value: "487" },
      { id: "Navsari ", value: "490" },
      { id: "Panch Mahals", value: "484" },
      { id: "Patan", value: "470" },
      { id: "Porbandar", value: "478" },
      { id: "Rajkot", value: "476" },
      { id: "Sabar Kantha", value: "472" },
      { id: "Surat", value: "492" },
      { id: "Surendranagar", value: "475" },
      { id: "Tapi", value: "493" },
      { id: "Vadodara", value: "486" },
      { id: "Valsad", value: "491" },
    ],
  },
  {
    value: "96",
    label: "Haryana",
    records: [
      { id: "Ambala", value: "70" },
      { id: "Bhiwani", value: "81" },
      { id: "Charkhi Dadri", value: "719" },
      { id: "Faridabad", value: "88" },
      { id: "Fatehabad", value: "78" },
      { id: "Gurgaon", value: "86" },
      { id: "Hisar", value: "80" },
      { id: "Jhajjar", value: "83" },
      { id: "Jind", value: "77" },
      { id: "Kaithal", value: "73" },
      { id: "Karnal", value: "74" },
      { id: "Kurukshetra", value: "72" },
      { id: "Mahendragarh", value: "84" },
      { id: "Nuh", value: "720" },
      { id: "Palwal ", value: "89" },
      { id: "Panchkula", value: "69" },
      { id: "Panipat", value: "75" },
      { id: "Rewari", value: "85" },
      { id: "Rohtak", value: "82" },
      { id: "Sirsa", value: "79" },
      { id: "Sonipat", value: "76" },
      { id: "Yamunanagar", value: "71" },
    ],
  },
  {
    value: "92",
    label: "Himachal Pradesh",
    records: [
      { id: "Bilaspur", value: "30" },
      { id: "Chamba", value: "23" },
      { id: "Hamirpur", value: "28" },
      { id: "Kangra", value: "24" },
      { id: "Kinnaur", value: "34" },
      { id: "Kullu", value: "26" },
      { id: "Lahul & Spiti", value: "25" },
      { id: "Mandi", value: "27" },
      { id: "Shimla", value: "33" },
      { id: "Sirmaur", value: "32" },
      { id: "Solan", value: "31" },
      { id: "Una", value: "29" },
    ],
  },
  {
    value: "91",
    label: "Jammu and Kashmir",
    records: [
      { id: "Anantnag", value: "14" },
      { id: "Badgam", value: "2" },
      { id: "Bandipore", value: "9" },
      { id: "Baramula", value: "8" },
      { id: "Doda", value: "16" },
      { id: "Ganderbal", value: "11" },
      { id: "Jammu", value: "21" },
      { id: "Kathua", value: "7" },
      { id: "Kishtwar", value: "18" },
      { id: "Kulgam", value: "15" },
      { id: "Kupwara", value: "1" },
      { id: "Poonch", value: "5" },
      { id: "Pulwama", value: "12" },
      { id: "Rajouri", value: "6" },
      { id: "Ramban", value: "17" },
      { id: "Reasi", value: "20" },
      { id: "Samba", value: "22" },
      { id: "Shopian", value: "13" },
      { id: "Srinagar", value: "10" },
      { id: "Udhampur", value: "19" },
    ],
  },
  {
    value: "20",
    label: "Jharkhand",
    records: [
      { id: "Bokaro", value: "355" },
      { id: "Chatra", value: "347" },
      { id: "Deoghar", value: "350" },
      { id: "Dhanbad", value: "354" },
      { id: "Dumka", value: "362" },
      { id: "Garhwa", value: "346" },
      { id: "Giridih", value: "349" },
      { id: "Godda", value: "351" },
      { id: "Gumla", value: "366" },
      { id: "Hazaribagh", value: "360" },
      { id: "Jamtara", value: "363" },
      { id: "Khunti", value: "365" },
      { id: "Kodarma", value: "348" },
      { id: "Latehar", value: "359" },
      { id: "Lohardaga", value: "356" },
      { id: "Pakur", value: "353" },
      { id: "Palamu", value: "358" },
      { id: "Pashchimi Singhbhum", value: "368" },
      { id: "Purbi Singhbhum", value: "357" },
      { id: "Ramgarh", value: "361" },
      { id: "Ranchi", value: "364" },
      { id: "Sahibganj", value: "352" },
      { id: "Saraikela-Kharsawan", value: "369" },
      { id: "Simdega", value: "367" },
    ],
  },
  {
    value: "29",
    label: "Karnataka",
    records: [
      { id: "Bagalkot", value: "556" },
      { id: "Ballari", value: "565" },
      { id: "Bangalore Rural", value: "583" },
      { id: "Bangalore Urban", value: "572" },
      { id: "Belagavi", value: "555" },
      { id: "Bidar", value: "558" },
      { id: "Chamarajanagar", value: "578" },
      { id: "Chikkaballapura", value: "582" },
      { id: "Chikmagalur", value: "570" },
      { id: "Chitradurga", value: "566" },
      { id: "Dakshina Kannada", value: "575" },
      { id: "Davanagere", value: "567" },
      { id: "Dharwad", value: "562" },
      { id: "Gadag", value: "561" },
      { id: "Hassan", value: "574" },
      { id: "Haveri", value: "564" },
      { id: "Kalaburagi", value: "721" },
      { id: "Kodagu", value: "576" },
      { id: "Kolar", value: "581" },
      { id: "Koppal", value: "560" },
      { id: "Mandya", value: "573" },
      { id: "Mysore", value: "577" },
      { id: "Raichur", value: "559" },
      { id: "Ramanagara", value: "584" },
      { id: "Shimoga", value: "568" },
      { id: "Tumkur", value: "571" },
      { id: "Udupi", value: "569" },
      { id: "Uttara Kannada", value: "563" },
      { id: "Vijayapura", value: "722" },
      { id: "Yadgir", value: "580" },
    ],
  },
  {
    value: "32",
    label: "Kerala",
    records: [
      { id: "Alappuzha", value: "598" },
      { id: "Ernakulam", value: "595" },
      { id: "Idukki", value: "596" },
      { id: "Kannur", value: "589" },
      { id: "Kasaragod", value: "588" },
      { id: "Kollam", value: "600" },
      { id: "Kottayam", value: "597" },
      { id: "Kozhikode", value: "591" },
      { id: "Malappuram", value: "592" },
      { id: "Palakkad", value: "593" },
      { id: "Pathanamthitta", value: "599" },
      { id: "Thiruvananthapuram", value: "601" },
      { id: "Thrissur", value: "594" },
      { id: "Wayanad", value: "590" },
    ],
  },
  {
    value: "37",
    label: "Ladakh",
    records: [
      { id: "Kargil", value: "4" },
      { id: "Leh(Ladakh)", value: "3" },
    ],
  },
  {
    value: "31",
    label: "Lakshadweep",
    records: [{ id: "Lakshadweep", value: "587" }],
  },
  {
    value: "23",
    label: "Madhya Pradesh",
    records: [
      { id: "Agar Malwa", value: "641" },
      { id: "Alirajpur", value: "465" },
      { id: "Anuppur", value: "461" },
      { id: "Ashoknagar", value: "459" },
      { id: "Balaghat", value: "457" },
      { id: "Barwani", value: "441" },
      { id: "Betul", value: "447" },
      { id: "Bhind", value: "420" },
      { id: "Bhopal", value: "444" },
      { id: "Burhanpur", value: "467" },
      { id: "Chhatarpur", value: "425" },
      { id: "Chhindwara", value: "455" },
      { id: "Damoh", value: "428" },
      { id: "Datia", value: "422" },
      { id: "Dewas", value: "437" },
      { id: "Dhar", value: "438" },
      { id: "Dindori", value: "453" },
      { id: "Guna", value: "458" },
      { id: "Gwalior", value: "421" },
      { id: "Harda", value: "448" },
      { id: "Hoshangabad", value: "449" },
      { id: "Indore", value: "439" },
      { id: "Jabalpur", value: "451" },
      { id: "Jhabua", value: "464" },
      { id: "Katni", value: "450" },
      { id: "Khandwa (East Nimar)", value: "466" },
      { id: "Khargone (West Nimar)", value: "440" },
      { id: "Mandla", value: "454" },
      { id: "Mandsaur", value: "433" },
      { id: "Morena", value: "419" },
      { id: "Narsimhapur", value: "452" },
      { id: "Neemuch", value: "432" },
      { id: "Niwari", value: "723" },
      { id: "Panna", value: "426" },
      { id: "Raisen", value: "446" },
      { id: "Rajgarh", value: "442" },
      { id: "Ratlam", value: "434" },
      { id: "Rewa", value: "430" },
      { id: "Sagar", value: "427" },
      { id: "Satna", value: "429" },
      { id: "Sehore", value: "445" },
      { id: "Seoni", value: "456" },
      { id: "Shahdol", value: "460" },
      { id: "Shajapur", value: "436" },
      { id: "Sheopur ", value: "418" },
      { id: "Shivpuri", value: "423" },
      { id: "Sidhi", value: "462" },
      { id: "Singrauli", value: "463" },
      { id: "Tikamgarh", value: "424" },
      { id: "Ujjain", value: "435" },
      { id: "Umaria", value: "431" },
      { id: "Vidisha", value: "443" },
    ],
  },
  {
    value: "27",
    label: "Maharashtra",
    records: [
      { id: "Ahmadnagar", value: "522" },
      { id: "Akola", value: "501" },
      { id: "Amravati", value: "503" },
      { id: "Aurangabad", value: "515" },
      { id: "Bhandara", value: "506" },
      { id: "Bid", value: "523" },
      { id: "Buldana", value: "500" },
      { id: "Chandrapur", value: "509" },
      { id: "Dhule", value: "498" },
      { id: "Gadchiroli", value: "508" },
      { id: "Gondiya", value: "507" },
      { id: "Hingoli", value: "512" },
      { id: "Jalgaon", value: "499" },
      { id: "Jalna", value: "514" },
      { id: "Kolhapur", value: "530" },
      { id: "Latur", value: "524" },
      { id: "Mumbai", value: "519" },
      { id: "Mumbai Suburban", value: "518" },
      { id: "Nagpur", value: "505" },
      { id: "Nanded", value: "511" },
      { id: "Nandurbar", value: "497" },
      { id: "Nashik", value: "516" },
      { id: "Osmanabad", value: "525" },
      { id: "Palghar", value: "669" },
      { id: "Parbhani", value: "513" },
      { id: "Pune", value: "521" },
      { id: "Raigarh", value: "520" },
      { id: "Ratnagiri", value: "528" },
      { id: "Sangli", value: "531" },
      { id: "Satara", value: "527" },
      { id: "Sindhudurg", value: "529" },
      { id: "Solapur", value: "526" },
      { id: "Thane", value: "517" },
      { id: "Wardha", value: "504" },
      { id: "Washim", value: "502" },
      { id: "Yavatmal", value: "510" },
    ],
  },
  {
    value: "14",
    label: "Manipur",
    records: [
      { id: "Bishnupur", value: "275" },
      { id: "Chandel", value: "280" },
      { id: "Churachandpur", value: "274" },
      { id: "Imphal East", value: "278" },
      { id: "Imphal West", value: "277" },
      { id: "Jiribam", value: "724" },
      { id: "Kakching", value: "725" },
      { id: "Kamjong", value: "726" },
      { id: "Kangpokpi", value: "727" },
      { id: "Noney", value: "728" },
      { id: "Pherzawl", value: "729" },
      { id: "Senapati", value: "272" },
      { id: "Tamenglong", value: "273" },
      { id: "Tengnoupal", value: "730" },
      { id: "Thoubal", value: "276" },
      { id: "Ukhrul", value: "279" },
    ],
  },
  {
    value: "17",
    label: "Meghalaya",
    records: [
      { id: "East Garo Hills", value: "294" },
      { id: "East Jaintia Hills", value: "660" },
      { id: "East Khasi Hills", value: "298" },
      { id: "North Garo Hills", value: "659" },
      { id: "Ribhoi", value: "297" },
      { id: "South Garo Hills", value: "295" },
      { id: "South West Garo Hills", value: "662" },
      { id: "South West Khasi Hills", value: "661" },
      { id: "West Garo Hills", value: "293" },
      { id: "West Jaintia Hills", value: "658" },
      { id: "West Khasi Hills", value: "296" },
    ],
  },
  {
    value: "15",
    label: "Mizoram",
    records: [
      { id: "Aizawl", value: "283" },
      { id: "Champhai", value: "284" },
      { id: "Kolasib", value: "282" },
      { id: "Lawngtlai", value: "287" },
      { id: "Lunglei", value: "286" },
      { id: "Mamit", value: "281" },
      { id: "Saiha", value: "288" },
      { id: "Serchhip", value: "285" },
    ],
  },
  {
    value: "13",
    label: "Nagaland",
    records: [
      { id: "Dimapur", value: "265" },
      { id: "Kiphire", value: "269" },
      { id: "Kohima", value: "270" },
      { id: "Longleng", value: "268" },
      { id: "Mokokchung", value: "262" },
      { id: "Mon", value: "261" },
      { id: "Noklak", value: "736" },
      { id: "Peren", value: "271" },
      { id: "Phek", value: "266" },
      { id: "Tuensang", value: "267" },
      { id: "Wokha", value: "264" },
      { id: "Zunheboto", value: "263" },
    ],
  },
  {
    value: "21",
    label: "Odisha",
    records: [
      { id: "Angul", value: "384" },
      { id: "Balangir", value: "393" },
      { id: "Baleshwar", value: "377" },
      { id: "Bargarh", value: "382" },
      { id: "Baudh", value: "391" },
      { id: "Bhadrak", value: "378" },
      { id: "Cuttack", value: "381" },
      { id: "Debagarh", value: "373" },
      { id: "Dhenkanal", value: "383" },
      { id: "Gajapati", value: "389" },
      { id: "Ganjam", value: "388" },
      { id: "Jagatsinghapur", value: "380" },
      { id: "Jajapur ", value: "370" },
      { id: "Jharsuguda", value: "371" },
      { id: "Kalahandi", value: "395" },
      { id: "Kandhamal", value: "390" },
      { id: "Kendrapara ", value: "379" },
      { id: "Kendujhar", value: "375" },
      { id: "Khordha", value: "386" },
      { id: "Koraput", value: "398" },
      { id: "Malkangiri", value: "399" },
      { id: "Mayurbhanj", value: "376" },
      { id: "Nabarangapur", value: "397" },
      { id: "Nayagarh ", value: "385" },
      { id: "Nuapada", value: "394" },
      { id: "Puri", value: "387" },
      { id: "Rayagada", value: "396" },
      { id: "Sambalpur", value: "372" },
      { id: "Subarnapur", value: "392" },
      { id: "Sundargarh", value: "374" },
    ],
  },
  {
    value: "34",
    label: "Puducherry",
    records: [
      { id: "Karaikal", value: "637" },
      { id: "Mahe", value: "636" },
      { id: "Puducherry", value: "635" },
      { id: "Yanam", value: "634" },
    ],
  },
  {
    value: "93",
    label: "Punjab",
    records: [
      { id: "Amritsar", value: "49" },
      { id: "Barnala", value: "54" },
      { id: "Bathinda", value: "46" },
      { id: "Faridkot", value: "45" },
      { id: "Fatehgarh Sahib", value: "40" },
      { id: "Fazilka", value: "663" },
      { id: "Firozpur", value: "43" },
      { id: "Gurdaspur", value: "35" },
      { id: "Hoshiarpur", value: "38" },
      { id: "Jalandhar", value: "37" },
      { id: "Kapurthala", value: "36" },
      { id: "Ludhiana", value: "41" },
      { id: "Mansa", value: "47" },
      { id: "Moga", value: "42" },
      { id: "Muktsar", value: "44" },
      { id: "Pathankot", value: "664" },
      { id: "Patiala", value: "48" },
      { id: "Rupnagar", value: "51" },
      { id: "Sahibzada Ajit Singh Nagar", value: "52" },
      { id: "Sangrur", value: "53" },
      { id: "Shahid Bhagat Singh Nagar ", value: "39" },
      { id: "Tarn Taran", value: "50" },
    ],
  },
  {
    value: "98",
    label: "Rajasthan",
    records: [
      { id: "Ajmer", value: "119" },
      { id: "Alwar", value: "104" },
      { id: "Banswara", value: "125" },
      { id: "Baran", value: "128" },
      { id: "Barmer", value: "115" },
      { id: "Bharatpur", value: "105" },
      { id: "Bhilwara", value: "122" },
      { id: "Bikaner", value: "101" },
      { id: "Bundi", value: "121" },
      { id: "Chittaurgarh", value: "126" },
      { id: "Churu", value: "102" },
      { id: "Dausa", value: "109" },
      { id: "Dhaulpur", value: "106" },
      { id: "Dungarpur", value: "124" },
      { id: "Ganganagar", value: "99" },
      { id: "Hanumangarh", value: "100" },
      { id: "Jaipur", value: "110" },
      { id: "Jaisalmer", value: "114" },
      { id: "Jalor", value: "116" },
      { id: "Jhalawar", value: "129" },
      { id: "Jhunjhunun", value: "103" },
      { id: "Jodhpur", value: "113" },
      { id: "Karauli", value: "107" },
      { id: "Kota", value: "127" },
      { id: "Nagaur", value: "112" },
      { id: "Pali", value: "118" },
      { id: "Pratapgarh", value: "131" },
      { id: "Rajsamand", value: "123" },
      { id: "Sawai Madhopur", value: "108" },
      { id: "Sikar", value: "111" },
      { id: "Sirohi", value: "117" },
      { id: "Tonk", value: "120" },
      { id: "Udaipur", value: "130" },
    ],
  },
  {
    value: "11",
    label: "Sikkim",
    records: [
      { id: "East District", value: "244" },
      { id: "North District", value: "241" },
      { id: "South District", value: "243" },
      { id: "West District", value: "242" },
    ],
  },
  {
    value: "33",
    label: "Tamil Nadu",
    records: [
      { id: "Ariyalur", value: "616" },
      { id: "Chengalpattu", value: "735" },
      { id: "Chennai", value: "603" },
      { id: "Coimbatore", value: "632" },
      { id: "Cuddalore", value: "617" },
      { id: "Dharmapuri", value: "630" },
      { id: "Dindigul", value: "612" },
      { id: "Erode", value: "610" },
      { id: "Kallakurichi", value: "733" },
      { id: "Kanchipuram", value: "604" },
      { id: "Kanyakumari", value: "629" },
      { id: "Karur", value: "613" },
      { id: "Krishnagiri", value: "631" },
      { id: "Madurai", value: "623" },
      { id: "Mayiladuthurai", value: "674" },
      { id: "Nagapattinam", value: "618" },
      { id: "Namakkal", value: "609" },
      { id: "Perambalur", value: "615" },
      { id: "Pudukkottai", value: "621" },
      { id: "Ramanathapuram", value: "626" },
      { id: "Ranipet", value: "731" },
      { id: "Salem", value: "608" },
      { id: "Sivaganga", value: "622" },
      { id: "Tenkasi", value: "747" },
      { id: "Thanjavur", value: "620" },
      { id: "Theni ", value: "624" },
      { id: "The Nilgiris", value: "611" },
      { id: "Thiruvallur", value: "602" },
      { id: "Thiruvarur", value: "619" },
      { id: "Thoothukkudi", value: "627" },
      { id: "Tiruchirappalli", value: "614" },
      { id: "Tirunelveli", value: "628" },
      { id: "Tirupattur", value: "732" },
      { id: "Tiruppur", value: "633" },
      { id: "Tiruvannamalai", value: "606" },
      { id: "Vellore", value: "605" },
      { id: "Viluppuram", value: "607" },
      { id: "Virudhunagar", value: "625" },
    ],
  },
  {
    value: "36",
    label: "Telangana",
    records: [
      { id: "Adilabad", value: "901" },
      { id: "Bhadradri Kothagudem", value: "911" },
      { id: "Hanumakonda", value: "677" },
      { id: "Hyderabad", value: "902" },
      { id: "Jagtial", value: "912" },
      { id: "Jangaon", value: "913" },
      { id: "Jayashankar Bhupalpally", value: "914" },
      { id: "Jogulamba Gadwal", value: "915" },
      { id: "Kamareddy", value: "916" },
      { id: "Karimnagar", value: "903" },
      { id: "Khammam", value: "904" },
      { id: "Kumaram Bheem Asifabad", value: "917" },
      { id: "Mahabubabad", value: "918" },
      { id: "Mahbubnagar", value: "905" },
      { id: "Mancherial", value: "919" },
      { id: "Medak", value: "906" },
      { id: "Medchal Malkajgiri", value: "920" },
      { id: "Mulugu", value: "998" },
      { id: "Nagarkurnool", value: "921" },
      { id: "Nalgonda", value: "999" },
      { id: "Nirmal", value: "922" },
      { id: "Nizamabad", value: "907" },
      { id: "Peddapalli", value: "923" },
      { id: "Rajanna Sircilla", value: "924" },
      { id: "Rangareddy", value: "908" },
      { id: "Sangareddy", value: "925" },
      { id: "Siddipet", value: "926" },
      { id: "Suryapet", value: "927" },
      { id: "Vikarabad", value: "931" },
      { id: "Wanaparthy", value: "928" },
      { id: "Warangal (Rural)", value: "909" },
      { id: "Warangal (Urban)", value: "910" },
      { id: "Yadadri Bhuvanagiri", value: "930" },
    ],
  },
  {
    value: "16",
    label: "Tripura",
    records: [
      { id: "Dhalai", value: "291" },
      { id: "Gomati", value: "667" },
      { id: "Khowai", value: "665" },
      { id: "North Tripura", value: "292" },
      { id: "Sepahijala", value: "666" },
      { id: "South Tripura", value: "290" },
      { id: "Unakoti", value: "668" },
      { id: "West Tripura", value: "289" },
    ],
  },
  {
    value: "95",
    label: "Uttarakhand",
    records: [
      { id: "Almora", value: "64" },
      { id: "Bageshwar", value: "63" },
      { id: "Chamoli", value: "57" },
      { id: "Champawat", value: "65" },
      { id: "Dehradun", value: "60" },
      { id: "Haridwar", value: "68" },
      { id: "Nainital", value: "66" },
      { id: "Pauri Garhwal", value: "61" },
      { id: "Pithoragarh", value: "62" },
      { id: "Rudraprayag", value: "58" },
      { id: "Tehri Garhwal", value: "59" },
      { id: "Udham Singh Nagar", value: "67" },
      { id: "Uttarkashi", value: "56" },
    ],
  },
  {
    value: "99",
    label: "Uttar Pradesh",
    records: [
      { id: "Agra", value: "146" },
      { id: "Aligarh", value: "143" },
      { id: "Ambedkar Nagar", value: "178" },
      { id: "Amethi", value: "734" },
      { id: "Amroha", value: "670" },
      { id: "Auraiya", value: "162" },
      { id: "Ayodhya", value: "177" },
      { id: "Azamgarh", value: "191" },
      { id: "Baghpat", value: "139" },
      { id: "Bahraich", value: "180" },
      { id: "Ballia", value: "193" },
      { id: "Balrampur", value: "182" },
      { id: "Banda", value: "170" },
      { id: "Bara Banki", value: "176" },
      { id: "Bareilly", value: "150" },
      { id: "Basti", value: "185" },
      { id: "Bhadohi", value: "198" },
      { id: "Bijnor", value: "134" },
      { id: "Budaun", value: "149" },
      { id: "Bulandshahr", value: "142" },
      { id: "Chandauli", value: "196" },
      { id: "Chitrakoot", value: "171" },
      { id: "Deoria", value: "190" },
      { id: "Etah", value: "201" },
      { id: "Etawah", value: "161" },
      { id: "Farrukhabad", value: "159" },
      { id: "Fatehpur", value: "172" },
      { id: "Firozabad", value: "147" },
      { id: "Gautam Buddha Nagar", value: "141" },
      { id: "Ghaziabad", value: "140" },
      { id: "Ghazipur", value: "195" },
      { id: "Gonda", value: "183" },
      { id: "Gorakhpur", value: "188" },
      { id: "Hamirpur", value: "168" },
      { id: "Hapur", value: "801" },
      { id: "Hardoi", value: "155" },
      { id: "Hathras", value: "675" },
      { id: "Jalaun", value: "165" },
      { id: "Jaunpur", value: "194" },
      { id: "Jhansi", value: "166" },
      { id: "Kannauj", value: "160" },
      { id: "Kanpur Dehat", value: "163" },
      { id: "Kanpur Nagar", value: "164" },
      { id: "Kasganj", value: "202" },
      { id: "Kaushambi", value: "174" },
      { id: "Kushinagar", value: "189" },
      { id: "Lakhimpur Kheri", value: "153" },
      { id: "Lalitpur", value: "167" },
      { id: "Lucknow", value: "157" },
      { id: "Maharajganj", value: "187" },
      { id: "Mahoba", value: "169" },
      { id: "Mainpuri", value: "148" },
      { id: "Mathura", value: "145" },
      { id: "Mau", value: "192" },
      { id: "Meerut", value: "138" },
      { id: "Mirzapur", value: "199" },
      { id: "Moradabad", value: "135" },
      { id: "Muzaffarnagar", value: "133" },
      { id: "Pilibhit", value: "151" },
      { id: "Pratapgarh", value: "173" },
      { id: "Prayagraj", value: "175" },
      { id: "Raebareli", value: "158" },
      { id: "Rampur", value: "136" },
      { id: "Saharanpur", value: "132" },
      { id: "Sambhal", value: "802" },
      { id: "Sant Kabir Nagar", value: "186" },
      { id: "Shahjahanpur", value: "152" },
      { id: "Shamli", value: "672" },
      { id: "Shravasti", value: "181" },
      { id: "Siddharthnagar", value: "184" },
      { id: "Sitapur", value: "154" },
      { id: "Sonbhadra", value: "200" },
      { id: "Sultanpur", value: "179" },
      { id: "Unnao", value: "156" },
      { id: "Varanasi", value: "197" },
    ],
  },
  {
    value: "19",
    label: "West Bengal",
    records: [
      { id: "Alipurduar", value: "737" },
      { id: "Bankura", value: "339" },
      { id: "Birbhum", value: "334" },
      { id: "Cooch Behar", value: "741" },
      { id: "Dakshin Dinajpur", value: "331" },
      { id: "Darjeeling", value: "327" },
      { id: "Hooghly", value: "338" },
      { id: "Howrah", value: "341" },
      { id: "Jalpaiguri", value: "328" },
      { id: "Jhargram", value: "744" },
      { id: "Kalimpong", value: "745" },
      { id: "Kolkata", value: "342" },
      { id: "Maldah", value: "332" },
      { id: "Murshidabad ", value: "333" },
      { id: "Nadia", value: "336" },
      { id: "North Twenty Four Parganas", value: "337" },
      { id: "Paschim Bardhaman", value: "739" },
      { id: "Paschim Medinipur", value: "344" },
      { id: "Purba Bardhaman", value: "740" },
      { id: "Purba Medinipur", value: "345" },
      { id: "Purulia", value: "340" },
      { id: "South Twenty Four Parganas", value: "343" },
      { id: "Uttar Dinajpur", value: "330" },
    ],
  },
];

export const bloogGroup = [
  { value: "18", type: "AB-ve" },
  { value: "17", type: "AB+ve" },
  { value: "12", type: "A-ve" },
  { value: "11", type: "A+ve" },
  { value: "14", type: "B-ve" },
  { value: "13", type: "B+ve" },
  { value: "23", type: "oh-ve" },
  { value: "22", type: "oh+ve" },
  { value: "16", type: "O-ve" },
  { value: "15", type: "O+ve" },
  { value: "all", type: "All" },
];
